LLM_engines:
  Qwen3-0.6B:
    instances:
      - id: "qwen3"
        host: "localhost"
        port: 8002
        cuda_device: 0
      - id: "qwen3-2"
        host: "localhost"
        port: 8004
        cuda_device: 0

    model_config:
      model_tag: "Qwen/Qwen3-0.6B"
      dtype: "float16"
      max_model_len: 500
      gpu_memory_utilization: 0.35
      tensor_parallel_size: 1

embedding_server:
  host: "localhost"
  port: 8003
  cuda_device: 0 

  embedding_models:
    m3e-base:
      model_name: "moka-ai/m3e-base"
      model_path: "./embedding_reranker_server/embedding_engine/model/embedding_model/m3e-base-model"
      tokenizer_path: "./embedding_reranker_server/embedding_engine/model/embedding_model/m3e-base-tokenizer"
      max_length: 512
      use_gpu: true
      use_float16: true

  reranking_models:
    bge-reranker-large:
      model_name: "BAAI/bge-reranker-large"
      model_path: "./embedding_reranker_server/embedding_engine/model/reranking_model/bge-reranker-large-model"
      tokenizer_path: "./embedding_reranker_server/embedding_engine/model/reranking_model/bge-reranker-large-tokenizer"
      max_length: 512
      use_gpu: true
      use_float16: true


