"""Pure dialect logic for the DB driver layer (no live DB needed)."""
import os
import sys

import pytest

PKG_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PKG_ROOT not in sys.path:
    sys.path.insert(0, PKG_ROOT)

from _driver import (  # noqa: E402
    _rowcount_from_status,
    dialectize_schema_pg,
    make_driver,
    split_statements,
    translate_placeholders,
)

pytestmark = pytest.mark.unit


def test_translate_placeholders_positional():
    assert translate_placeholders("a=? AND b=?") == "a=$1 AND b=$2"
    assert translate_placeholders("no params") == "no params"


def test_dialectize_autoincrement_and_real():
    pg = dialectize_schema_pg("id INTEGER PRIMARY KEY AUTOINCREMENT, ts REAL NOT NULL")
    assert "GENERATED BY DEFAULT AS IDENTITY" in pg
    assert "AUTOINCREMENT" not in pg
    assert "DOUBLE PRECISION" in pg and "REAL" not in pg


def test_split_strips_comment_with_semicolon():
    # A schema comment can contain ';' — it must not split the statement.
    script = (
        "CREATE TABLE t (\n"
        "  a INTEGER,  -- max per period; NULL = unlimited\n"
        "  b TEXT\n"
        ");\n"
        "CREATE INDEX i ON t(a);"
    )
    stmts = split_statements(script)
    assert len(stmts) == 2
    assert stmts[0].startswith("CREATE TABLE t") and "NULL = unlimited" not in stmts[0]


def test_rowcount_parsing():
    assert _rowcount_from_status("DELETE 3") == 3
    assert _rowcount_from_status("UPDATE 0") == 0
    assert _rowcount_from_status("INSERT 0 2") == 2
    assert _rowcount_from_status("WEIRD") == 0


def test_make_driver_selects_backend():
    assert make_driver("/tmp/x.db", None).dialect == "sqlite"
    assert make_driver(None, "postgresql://h/db").dialect == "postgres"
