"""DB driver layer: one async DB interface, two backends (SQLite / Postgres).

`LLMOpsStore` writes plain SQL with `?` placeholders and reads rows by name/index.
This module keeps that surface unchanged while letting the same code run on either
SQLite (the zero-config single-machine default) or Postgres (for HA — multiple
backend replicas sharing one networked DB). See docs/ha-phase2-design_zh-CN.md §2a.

Both drivers expose the small interface the store uses:
  await driver.execute(sql, params) -> cursor (.fetchone()/.fetchall()/.rowcount)
  await driver.insert(sql, params)  -> new autoincrement id
  await driver.executescript(script)
  await driver.ensure_column(table, col, decl)   # idempotent migration
  await driver.commit()  / await driver.close()

The store's SQL is dialect-portable (no SQLite-only functions); the only
differences — `?`->`$n`, AUTOINCREMENT, RETURNING-id, REAL->DOUBLE PRECISION,
column-existence checks — are normalised here.
"""
from __future__ import annotations

import os
import re

import aiosqlite


# ---- dialect helpers (pure; unit-tested without a live DB) ----------------

def translate_placeholders(sql: str) -> str:
    """`?` positional placeholders -> Postgres `$1, $2, …`. The store never puts a
    literal `?` inside a string literal, so a straight positional pass is safe."""
    out, n = [], 0
    for ch in sql:
        if ch == "?":
            n += 1
            out.append(f"${n}")
        else:
            out.append(ch)
    return "".join(out)


def dialectize_schema_pg(script: str) -> str:
    """Rewrite the SQLite CREATE script for Postgres."""
    script = script.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    # epoch-second timestamps + floats: REAL -> DOUBLE PRECISION.
    script = re.sub(r"\bREAL\b", "DOUBLE PRECISION", script)
    return script


def split_statements(script: str) -> list[str]:
    """Split a multi-statement script into individual statements (asyncpg runs one
    command per execute). Strips `--` line comments first, since a schema comment
    can contain a `;` (e.g. "quota_period; NULL = unlimited") that would otherwise
    split mid-statement."""
    no_comments = "\n".join(line.split("--", 1)[0] for line in script.splitlines())
    return [s.strip() for s in no_comments.split(";") if s.strip()]


def _returns_rows(sql: str) -> bool:
    head = sql.lstrip()[:6].upper()
    return head.startswith("SELECT") or "RETURNING" in sql.upper()


def _pg_type(decl: str) -> str:
    return "DOUBLE PRECISION" if decl.strip().upper() == "REAL" else decl


def _rowcount_from_status(status: str) -> int:
    # asyncpg execute() returns e.g. "UPDATE 3" / "DELETE 1" / "INSERT 0 2".
    try:
        return int(status.split()[-1])
    except (ValueError, IndexError):
        return 0


# ---- SQLite ---------------------------------------------------------------

class SqliteDriver:
    dialect = "sqlite"

    def __init__(self, db_path: str) -> None:
        self.db_path = db_path
        self._conn: aiosqlite.Connection | None = None

    async def connect(self) -> "SqliteDriver":
        if os.path.dirname(self.db_path):
            os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        # autocommit (isolation_level=None): every statement self-commits, so a
        # write that loses the WAL lock can't leave a dangling transaction.
        self._conn = await aiosqlite.connect(self.db_path, isolation_level=None)
        self._conn.row_factory = aiosqlite.Row
        await self._conn.execute("PRAGMA journal_mode=WAL")
        await self._conn.execute("PRAGMA synchronous=NORMAL")
        await self._conn.execute("PRAGMA busy_timeout=30000")
        return self

    async def execute(self, sql: str, params=()):
        return await self._conn.execute(sql, params)

    async def executescript(self, script: str) -> None:
        await self._conn.executescript(script)

    async def insert(self, sql: str, params=()) -> int:
        cur = await self._conn.execute(sql, params)
        return cur.lastrowid

    async def ensure_column(self, table: str, column: str, decl: str) -> None:
        cur = await self._conn.execute(f"PRAGMA table_info({table})")
        cols = {row["name"] for row in await cur.fetchall()}
        if column not in cols:
            await self._conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {decl}")

    async def commit(self) -> None:
        await self._conn.commit()

    async def close(self) -> None:
        if self._conn is not None:
            await self._conn.close()
            self._conn = None


# ---- Postgres -------------------------------------------------------------

class _PgCursor:
    """Mimics the slice of aiosqlite's cursor the store uses."""

    def __init__(self, rows, rowcount: int) -> None:
        self._rows = rows
        self.rowcount = rowcount
        self.lastrowid = None  # PG ids come back via insert()/RETURNING, not here

    async def fetchone(self):
        return self._rows[0] if self._rows else None

    async def fetchall(self):
        return self._rows


class PgDriver:
    dialect = "postgres"

    def __init__(self, dsn: str) -> None:
        self.dsn = dsn
        self._pool = None

    async def connect(self) -> "PgDriver":
        import asyncpg  # lazy: only needed in HA mode, not for SQLite installs

        # A pool (not a single connection): asyncpg connections aren't safe for
        # concurrent queries, but the backend/router fire many in parallel.
        self._pool = await asyncpg.create_pool(self.dsn, min_size=1, max_size=10)
        return self

    async def execute(self, sql: str, params=()):
        tsql = translate_placeholders(sql)
        async with self._pool.acquire() as conn:
            if _returns_rows(sql):
                rows = await conn.fetch(tsql, *params)
                return _PgCursor(rows, len(rows))
            status = await conn.execute(tsql, *params)
            return _PgCursor([], _rowcount_from_status(status))

    async def executescript(self, script: str) -> None:
        async with self._pool.acquire() as conn:
            for stmt in split_statements(dialectize_schema_pg(script)):
                await conn.execute(stmt)

    async def insert(self, sql: str, params=()) -> int:
        tsql = translate_placeholders(sql)
        if "RETURNING" not in sql.upper():
            tsql = tsql.rstrip().rstrip(";") + " RETURNING id"
        async with self._pool.acquire() as conn:
            return await conn.fetchval(tsql, *params)

    async def ensure_column(self, table: str, column: str, decl: str) -> None:
        async with self._pool.acquire() as conn:
            await conn.execute(
                f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {_pg_type(decl)}"
            )

    async def commit(self) -> None:
        pass  # asyncpg autocommits each execute outside an explicit transaction

    async def close(self) -> None:
        if self._pool is not None:
            await self._pool.close()
            self._pool = None


def make_driver(db_path: str | None, db_url: str | None):
    """Pick a driver: a `postgres://` URL -> Postgres, else SQLite at db_path."""
    if db_url:
        return PgDriver(db_url)
    return SqliteDriver(db_path)
